#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Writing',  url: 'Writing'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}


#-------------------------------
# Projects Section


projects:
- {name: 'Show Reel',                url: 'show-reel'}
- {name: 'Reflex',                   url: 'reflex'}
- {name: 'Ataraxia',                 url: 'ataraxia'}
- {name: 'Pigs and Courgettes',      url: 'pigs-and-courgettes'}
- {name: 'Alder',                    url: 'alder'}
- {name: 'Into Dust',                url: 'into-dust'}
- {name: 'Teenage Engineering',      url: 'teenage-engineering'}
- {name: 'Fyrhyl',                   url: 'fyrhyl'}
- {name: 'Mammabarn',                url: 'mammabarn'}



#-------------------------------
# Contact Section

social:
#- {icon: 'twitter',   link: '#'}
#- {icon: 'instagram', link: '#'}
#- {icon: 'github',    link: '#'}
#- {icon: 'linkedin',  link: '#'}
- {icon: 'envelope',  link: 'mailto:tom+web@syntheticdark.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
